source "http://rubygems.org"
gem "sinatra"
gem "sinatra-contrib"
gem "json"
gem "rake"
gem "google-api-client"
gem "crafty"
gem "htmlentities"
gem "logger"
gem "ruby-openid"
gem "ruby-openid-apps-discovery"
gem "rack-openid"
gem "oauth"
gem "rufus-scheduler"
gem 'mongoid', "~> 3.1.4"

group :test do
	gem "selenium-webdriver"
  gem "rack-test"
  gem "rspec"
  gem "cucumber"
  gem "capybara"
  gem "capybara-webkit"
  gem "builder"
  gem "listen"
end
