development:
  sessions:
    default:
      database: gexpiredb_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: gexpiredb_test
      hosts:
        - localhost:27017

production: 
  sessions: 
    default: 
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        skip_version_check: true